exclude: ["Rakefile", "Gemfile", "config.rb", "README.md", "sass"]

pygments: true

# General
title: Jairo G.
description: Costa Rica Web Engineer. Developer at
work: the hangar
work_url: thehangar.cr 
url: http://jgatjens.com
github_url: http://jgatjens.github.io
permalink: /:title
pygments: true

# Network usernames
twitter: jgatjens
github: jgatjens
linkedin: in/jgatjens
email: jgatjens@gmail.com
# themeforest: jgatjens