exclude: ["Rakefile", "Gemfile", "config.rb", "README.md", "sass"]

# General
title: Sonny T.
url: http://sonnyt.com
github_url: http://sonnyt.github.com

# Network usernames
twitter: sonnyt
github: sonnyt
linkedin: sonny-tulyaganov/18/964/910
email: hi@sonnyt.com
themeforest: sonnyt